version: '3'

services:
  api:
    container_name: server-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:3031'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - app-network
    command: >
      sh -c "
      npx prisma migrate deploy &&
      npm run start"

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: app
      POSTGRES_USER: mharbouli
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - "./docker-data/db:/var/lib/postgresql/data"

networks:
  app-network:
    driver: bridge

