version: '3'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: pacha
      POSTGRES_USER: pacha
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - "./docker-data/db:/var/lib/postgresql/data"

networks:
  app-network:
    driver: bridge
