
// This file is generated automatically by vite.config.ts
// Do not edit this file manually

const Env = {
  "VITE_APP_ENV": "development",
  "VITE_API_URL": "http://localhost:3031/api/v1",
  "VITE_VAR_NUMBER": 123,
  "VITE_VAR_BOOL": true
} as const;

export default Env;
